### ISSUE TITLE
Orb-agent: error after shutdown (stop/restart) the container

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#748]
Steps to reproduce:
<br>
1)
- provision an orb-agent container
- open container logs
- restart the container
- check the logs
<br>
2)
<br>

- provision an orb-agent container
- open container logs
- stop the container
- start the same container again
- try to stop/restart the container
- check the logs

<br>

* Note that on first stop of the container, no error occurs. But for the second on all shutdown generate an error

<br>

```
{"level":"info","ts":1641930374.9790275,"caller":"agent/agent.go:121","msg":"stopping agent"}
{"level":"info","ts":1641930375.6192598,"caller":"pktvisor/pktvisor.go:390","msg":"pktvisor stopping"}
{"level":"info","ts":1641930375.6193874,"caller":"pktvisor/pktvisor.go:253","msg":"pktvisor stdout","log":"[2022-01-11 19:46:15.619] [visor] [info] Shutting down"}
{"level":"info","ts":1641930375.6194284,"caller":"pktvisor/pktvisor.go:253","msg":"pktvisor stdout","log":"[2022-01-11 19:46:15.619] [visor] [info] policy [test_policy_name_DCjFBzgcOi]: stopping"}
{"level":"info","ts":1641930375.6194384,"caller":"pktvisor/pktvisor.go:253","msg":"pktvisor stdout","log":"[2022-01-11 19:46:15.619] [visor] [info] policy [test_policy_name_DCjFBzgcOi]: stopping input instance: default_pcap-test_policy_name_DCjFBzgcOi"}
{"level":"info","ts":1641930375.6645226,"caller":"pktvisor/pktvisor.go:253","msg":"pktvisor stdout","log":"[2022-01-11 19:46:15.664] [visor] [info] policy [test_policy_name_DCjFBzgcOi]: stopping handler instance: test_policy_name_DCjFBzgcOi-default_net"}
{"level":"info","ts":1641930375.6648157,"caller":"pktvisor/pktvisor.go:253","msg":"pktvisor stdout","log":"[2022-01-11 19:46:15.664] [visor] [info] exit with success"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x20d0b9b]

goroutine 75 [running]:
github.com/ns1labs/orb/agent/backend/pktvisor.(*pktvisorBackend).Stop(0xc00012a380)
	/go/src/github.com/ns1labs/orb/agent/backend/pktvisor/pktvisor.go:399 +0x25b
github.com/ns1labs/orb/agent.(*orbAgent).Stop(0xc0005b4900)
	/go/src/github.com/ns1labs/orb/agent/agent.go:130 +0x33b
main.Run.func1()
	/go/src/github.com/ns1labs/orb/cmd/agent/main.go:90 +0x4a
created by main.Run
	/go/src/github.com/ns1labs/orb/cmd/agent/main.go:88 +0x6b2

```

**Comment by manrodrigues** [comment]
Solved

```
{"level":"info","ts":1646058252.9436839,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:24:12.943] [visor] [info] Registering GET /api/v1/policies/([a-zA-Z_][a-zA-Z0-9_-]*)"}
{"level":"info","ts":1646058252.9436896,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:24:12.943] [visor] [info] Registering DELETE /api/v1/policies/([a-zA-Z_][a-zA-Z0-9_-]*)"}
{"level":"info","ts":1646058252.9437194,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:24:12.943] [visor] [info] Registering GET /api/v1/policies/([a-zA-Z_][a-zA-Z0-9_-]*)/metrics/(window|bucket)/(\\d+)"}
{"level":"info","ts":1646058252.9438126,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:24:12.943] [visor] [info] Registering GET /api/v1/policies/([a-zA-Z_][a-zA-Z0-9_-]*)/metrics/prometheus"}
{"level":"info","ts":1646058252.9438658,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:24:12.943] [visor] [info] tap [default_pcap]: parsing"}
{"level":"info","ts":1646058252.943958,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:24:12.943] [visor] [info] tap [default_pcap]: loaded, type pcap"}
{"level":"info","ts":1646058252.9440203,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:24:12.944] [visor] [info] sending anonymous usage metrics (once/day, use --no-track to disable): 0efacd4-poleved-0.1.4.pktvisord.metrics.pktvisor.dev."}
{"level":"info","ts":1646058252.9637923,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:24:12.963] [visor] [info] web server listening on localhost:10853"}
{"level":"info","ts":1646058253.937573,"caller":"pktvisor/pktvisor.go:273","msg":"pktvisor process started","pid":20}
{"level":"info","ts":1646058253.9943733,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:24:13.994] [visor] [info] REQUEST: GET /api/v1/metrics/app 200"}
{"level":"info","ts":1646058253.994755,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:24:13.994] [visor] [info] REQUEST: GET /api/v1/taps 200"}
{"level":"info","ts":1646058253.9948316,"caller":"agent/rpc_to.go:48","msg":"sending capabilities","value":"{\"schema_version\":\"1.0\",\"orb_agent\":{\"version\":\"0.12.0-develop\"},\"agent_tags\":null,\"backends\":{\"pktvisor\":{\"version\":\"4.1.0-develop-4dcafe0\",\"data\":{\"taps\":{\"default_pcap\":{\"config\":{\"iface\":\"wlo1\"},\"input_type\":\"pcap\",\"interface\":\"visor.module.input/1.0\"}}}}}}"}
```
```
{"level":"info","ts":1646058358.3443239,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:25:58.344] [visor] [info] Shutting down"}
{"level":"info","ts":1646058358.3446407,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:25:58.344] [visor] [info] exit with success"}
{"level":"info","ts":1646058358.3457928,"caller":"pktvisor/pktvisor.go:398","msg":"pktvisor process stopped","pid":20,"exit_code":0}
{"level":"info","ts":1646058371.6622396,"caller":"agent/agent.go:64","msg":"using local config db","filename":"./orb-agent.db"}
{"level":"info","ts":1646058371.6626375,"caller":"agent/agent.go:102","msg":"agent started","version":"0.12.0-develop"}
{"level":"info","ts":1646058371.6626563,"caller":"cloud_config/cloud_config.go:172","msg":"using explicitly specified cloud configuration","address":"tls://localhost:8883","id":"2e4f5f7a-5da3-4e21-8b68-47286699e6eb"}
{"level":"info","ts":1646058371.6626716,"caller":"agent/agent.go:78","msg":"registered backends","values":["pktvisor"]}
{"level":"info","ts":1646058371.6626775,"caller":"agent/agent.go:79","msg":"requested backends","values":{"pktvisor":{"api_host":"localhost","api_port":"10853","binary":"/usr/local/sbin/pktvisord","config_file":"/tmp/orb-agent-pktvisor-conf.wrCYYQ"}}}
{"level":"info","ts":1646058371.662718,"caller":"pktvisor/pktvisor.go:229","msg":"pktvisor startup","arguments":["--admin-api","-l","localhost","-p","10853","--config","/tmp/orb-agent-pktvisor-conf.wrCYYQ"]}
{"level":"info","ts":1646058371.669085,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.668] [visor] [info] pktvisor 4.1.0-develop-4dcafe0 starting up"}
{"level":"info","ts":1646058371.6691027,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Load input stream plugin: dnstap visor.module.input/1.0"}
{"level":"info","ts":1646058371.6691067,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Load input stream plugin: mock visor.module.input/1.0"}
{"level":"info","ts":1646058371.66911,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Load input stream plugin: pcap visor.module.input/1.0"}
{"level":"info","ts":1646058371.6691132,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Load input stream plugin: sflow visor.module.input/1.0"}
{"level":"info","ts":1646058371.669116,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Load stream handler plugin: dhcp visor.module.handler/1.0"}
{"level":"info","ts":1646058371.6691206,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Load stream handler plugin: dns visor.module.handler/1.0"}
{"level":"info","ts":1646058371.6691241,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Load stream handler plugin: net visor.module.handler/1.0"}
{"level":"info","ts":1646058371.6691272,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Load stream handler plugin: pcap visor.module.handler/1.0"}
{"level":"info","ts":1646058371.6691303,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Initialize server control plane"}
{"level":"info","ts":1646058371.669133,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering DELETE /api/v1/server"}
{"level":"info","ts":1646058371.669136,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering GET /api/v1/metrics/app"}
{"level":"info","ts":1646058371.6691391,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering GET /api/v1/metrics/rates"}
{"level":"info","ts":1646058371.6691425,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering GET /api/v1/metrics/bucket/(\\d+)"}
{"level":"info","ts":1646058371.6691468,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering GET /api/v1/metrics/window/(\\d+)"}
{"level":"info","ts":1646058371.6691809,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] enabling prometheus metrics for \"default\" policy on: /metrics"}
{"level":"info","ts":1646058371.6691942,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering GET /metrics"}
{"level":"info","ts":1646058371.669201,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering GET /api/v1/taps"}
{"level":"info","ts":1646058371.6692057,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering GET /api/v1/policies"}
{"level":"info","ts":1646058371.6692107,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering POST /api/v1/policies"}
{"level":"info","ts":1646058371.669215,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering GET /api/v1/policies/([a-zA-Z_][a-zA-Z0-9_-]*)"}
{"level":"info","ts":1646058371.6692195,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering DELETE /api/v1/policies/([a-zA-Z_][a-zA-Z0-9_-]*)"}
{"level":"info","ts":1646058371.6692927,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering GET /api/v1/policies/([a-zA-Z_][a-zA-Z0-9_-]*)/metrics/(window|bucket)/(\\d+)"}
{"level":"info","ts":1646058371.669368,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] Registering GET /api/v1/policies/([a-zA-Z_][a-zA-Z0-9_-]*)/metrics/prometheus"}
{"level":"info","ts":1646058371.6694472,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] tap [default_pcap]: parsing"}
{"level":"info","ts":1646058371.6695092,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] tap [default_pcap]: loaded, type pcap"}
{"level":"info","ts":1646058371.6695657,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.669] [visor] [info] sending anonymous usage metrics (once/day, use --no-track to disable): 0efacd4-poleved-0.1.4.pktvisord.metrics.pktvisor.dev."}
{"level":"info","ts":1646058371.6895518,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:11.689] [visor] [info] web server listening on localhost:10853"}
{"level":"info","ts":1646058372.6635122,"caller":"pktvisor/pktvisor.go:273","msg":"pktvisor process started","pid":21}
{"level":"info","ts":1646058372.7216277,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:12.721] [visor] [info] REQUEST: GET /api/v1/metrics/app 200"}
{"level":"info","ts":1646058372.7220902,"caller":"pktvisor/pktvisor.go:247","msg":"pktvisor stdout","log":"[2022-02-28 14:26:12.722] [visor] [info] REQUEST: GET /api/v1/taps 200"}
{"level":"info","ts":1646058372.7221653,"caller":"agent/rpc_to.go:48","msg":"sending capabilities","value":"{\"schema_version\":\"1.0\",\"orb_agent\":{\"version\":\"0.12.0-develop\"},\"agent_tags\":null,\"backends\":{\"pktvisor\":{\"version\":\"4.1.0-develop-4dcafe0\",\"data\":{\"taps\":{\"default_pcap\":{\"config\":{\"iface\":\"wlo1\"},\"input_type\":\"pcap\",\"interface\":\"visor.module.input/1.0\"}}}}}}"}
```
