### ISSUE TITLE
Agent: after reapplying edited policy, orb-agent shuts down after panic message

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#810]
Steps to reproduce:

1 - Apply a policy that fails to an agent
-  For this step you can use `only_qname_suffix` as a string:

```
{
    "name": "policy-failed",
    "tags": {},
    "backend": "pktvisor",
    "schema_version": "",
    "policy": {
        "handlers": {
            "modules": {
                "handler_dns_1": {
                    "filter": {
                        "only_qname_suffix": ".example.com"
                    },
                    "type": "dns"
                }
            }
        },
        "input": {
            "input_type": "pcap",
            "tap": "default_pcap"
        },
        "kind": "collection"
    }
}

```
These logs should be displayed on orc-agent container's logs:

```
{"level":"warn","ts":1643384409.2283533,"caller":"pktvisor/pktvisor.go:179","msg":"yaml policy application failure","policy_id":"5e3876e5-32f3-4a89-9a3d-bd1eaabe47be","policy":"version: \"1.0\"\nvisor:\n    policies:\n        policy-failed:\n            handlers:\n                modules:\n                    handler_dns_1:\n                        filter:\n                            only_qname_suffix: .example.com\n                        type: dns\n            input:\n                input_type: pcap\n                tap: default_pcap\n            kind: collection\n"}
{"level":"warn","ts":1643384409.2285242,"caller":"policyMgr/manager.go:168","msg":"policy failed to apply","policy_id":"5e3876e5-32f3-4a89-9a3d-bd1eaabe47be","policy_name":"policy-failed","error":"500 policy [policy-failed] failed to start: wrong type for key: only_qname_suffix"}

```

2 - Edit policy through the REST API changing `only_qname_suffix` for an array:

```
{
    "name": "policy-failed",
    "tags": {},
    "backend": "pktvisor",
    "schema_version": "",
    "policy": {
        "handlers": {
            "modules": {
                "handler_dns_1": {
                    "filter": {
                        "only_qname_suffix": [".example.com"]
                    },
                    "type": "dns"
                }
            }
        },
        "input": {
            "input_type": "pcap",
            "tap": "default_pcap"
        },
        "kind": "collection"
    }
}

```

3 - Create a new dataset applying this policy again to the agent
4 - Check orb-agent logs

Current result:
Pktvisor shuts down

```
{"level":"info","ts":1643386719.8134136,"caller":"policyMgr/manager.go:51","msg":"managing agent policy from core","action":"manage","name":"policy-failed","dataset":"a2b346cd-8d82-44c6-869e-12db5e64c777","backend":"pktvisor","id":"5e3876e5-32f3-4a89-9a3d-bd1eaabe47be","version":1}
panic: assignment to entry in nil map

goroutine 116 [running]:
github.com/ns1labs/orb/agent/policies.policyMemRepo.EnsureDataset(...)
	/go/src/github.com/ns1labs/orb/agent/policies/repo.go:54
github.com/ns1labs/orb/agent/policyMgr.(*policyManager).ManagePolicy(0xc00049fee0, {{0xc00076af60, 0x6}, {0xc00075a3c0, 0x24}, {0xc00075a3f0, 0x24}, {0xc00076af70, 0xd}, {0xc00076af68, ...}, ...})
	/go/src/github.com/ns1labs/orb/agent/policyMgr/manager.go:75 +0x6e3
github.com/ns1labs/orb/agent.(*orbAgent).handleAgentPolicies(0xc000760480, {0xc00014c340, 0x1, 0x238bea0})
	/go/src/github.com/ns1labs/orb/agent/rpc_from.go:31 +0x102
github.com/ns1labs/orb/agent.(*orbAgent).handleGroupRPCFromCore(0xc000760480, {0x0, 0x4}, {0x303a330, 0xc0004ce0a0})
	/go/src/github.com/ns1labs/orb/agent/rpc_from.go:65 +0x7a5
github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch.func2()
	/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.5/router.go:210 +0x8a4
created by github.com/eclipse/paho%2emqtt%2egolang.(*router).matchAndDispatch
	/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.5/router.go:169 +0x26f
arodrigues:~/Documents/orb (develop)$ 

```

**Comment by manrodrigues** [comment]
maybe related with #721

**Comment by manrodrigues** [comment]
Fixed. Last commit: https://github.com/ns1labs/orb/commit/599455d4142431bd35242c4dcb56ece7a3d76967

![after_edit_policy](https://user-images.githubusercontent.com/78241475/152526764-caeba607-ead8-4192-a727-60745507bd71.gif)


![reapply_policy_after_edition](https://user-images.githubusercontent.com/78241475/152526805-8852a481-76bd-4f6c-8c40-105fd36ae233.gif)
